NOAA-GSL/unified-graphics

.gitignore
Add some rules to the `.gitignore` for local development files and Node development.
=> Ignore local dev files

License.md
Add a `License.md` file with license text specified in the [NOAA GitHub Usage Guidelines](https://ufscommunity.org/wp-content/uploads/2019/11/20170823_NOAA_GitHub_Usage_Guidelines.pdf).
=> Add NOAA-approved license file

README.md
Add the standard NOAA disclaimer to the README. I also updated the description to describe the project as “experimental”, which seems common for projects that haven’t been transitioned to operations.
=> NOAA disclaimer

CONTRIBUTING.md, services/api/poetry.lock, services/api/pyproject.toml, services/api/src/unified_graphics/__init__.py, services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/tests/conftest.py, services/api/tests/test_diag.py, services/api/tests/test_unified_graphics.py
Define API for fetching temperature diagnostics as JSON over HTTP. For now there is no ability to choose a model run, since we have only one set of test files. We will focus on temperature first, and then add other variables.
=> Fetch diagnostics as JSON over HTTP

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/project.md
A few minor updates to the issue templates:
- Italicize texxt in the templates that is descriptive and should be replaced
- Add a “Rabbit Hole” section to the project template, since I’ve been putting that section in
=> Issue templates

services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/tests/test_diag.py, services/api/tests/test_unified_graphics.py
Refactoring the temperature endpoint to follow the same structure as the
wind endpoint because it's more composable and testable.
=> Refactor temperature diagnostics endpoint

services/ui/src/js/components/Histogram.js, services/ui/src/js/components/VectorMapDiag.js, services/ui/src/styles/_global.scss
Add histograms of the scalar components for the wind vectors to complement the map.
=> Wind histograms

services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/tests/test_diag.py, services/api/tests/test_unified_graphics.py, services/ui/src/index.html, services/ui/src/js/components/VectorMapDiag.js
Apply an Albers projection to the map. We’ve lost the diverging color scale for the time being because I calculate the magnitude from the $Obs - Forecast$ vector instead of calculating the forecast vector, then calculating the magnitude for both the observation and forecast, and then subtracting the magnitudes. For now I think this is fine. I think we’ll address this when we build a transformation pipeline (#67).
=> Map projection

services/ui/package-lock.json, services/ui/package.json, services/ui/src/index.html, services/ui/src/js/components/App/App.js, services/ui/src/js/components/App/index.js, services/ui/src/js/components/ChartMap/ChartMap.js, services/ui/src/js/components/ChartMap/index.js, services/ui/src/js/components/Header/Header.js, services/ui/src/js/components/Header/index.js, services/ui/src/js/components/VariableDiagnostic/VariableDiagnostic.js, services/ui/src/js/components/VariableDiagnostic/index.js, services/ui/src/js/components/VariableDiagnostic/useBrushedScalar.js, services/ui/src/js/main.js, services/ui/src/styles/_global.scss, services/ui/src/styles/_uswds-theme.scss, services/ui/src/styles/_utilities.scss
Implement a single-variable view for diagnosticts. Showing a single variable is both easier to build and maintain compared to a dashboard, and gives more space to the charts so that they can be more easily read.
=> Single Variable Diag View

services/ui/src/js/components/DiagnosticView/DiagnosticView.svelte, services/ui/src/js/components/LoadingSpinner/LoadingSpinner.js, services/ui/src/js/components/LoadingSpinner/index.js, services/ui/src/js/main.js, services/ui/src/styles/_default.scss, services/ui/src/styles/_reset.scss, services/ui/src/styles/_utilities.scss, services/ui/src/styles/index.scss
Display a loading indicator as an overlay instead of replacing the chart elements every time we load new data.
=> Loading indicator

services/ui/src/js/components/Chart2DHistogram/Chart2DHistogram.js, services/ui/src/js/components/ChartContainer/ChartContainer.js, services/ui/src/js/components/ColorRamp/ColorRamp.js, services/ui/src/js/components/ColorRamp/index.js, services/ui/src/js/components/DiagnosticView/LoopDisplay.svelte, services/ui/src/js/main.js, services/ui/src/styles/_default.scss
Implement a legend for the 2D histograms that communicates the scale of the color ramp for observation counts in the chart.
=> 2D Histogram Legend

services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/tests/conftest.py, services/api/tests/test_diag.py, services/api/tests/test_unified_graphics.py, services/ui/src/js/App.svelte, services/ui/src/js/components/Chart2DHistogram/Chart2DHistogram.js, services/ui/src/js/components/ChartHistogram/ChartHistogram.js, services/ui/src/js/components/ChartMap/ChartMap.js, services/ui/src/js/components/DiagnosticView/DiagnosticView.helpers.js, services/ui/src/js/components/DiagnosticView/DiagnosticView.svelte, services/ui/src/js/components/DiagnosticView/LoopDisplay.svelte, services/ui/src/js/components/Header/Header.svelte, services/ui/src/js/helpers.js
Move the filtering behavior out of the client and into the server. This change
will help simplify the client application, making it less error prone. All the
client will have to do is build URLs with parameters based on the selections in
the charts, it doesn't have to implement any filtering logic.
=> Server-side filtering

services/api/src/unified_graphics/diag.py, services/api/tests/conftest.py, services/api/tests/test_unified_graphics.py, services/ui/src/js/App.svelte, services/ui/src/js/components/DiagnosticView/DiagnosticView.svelte, services/ui/src/js/components/Header/Header.svelte
Filter out the unused observations in the data.
=> Filter observations by used flag

services/data/poetry.lock, services/data/pyproject.toml
fsspec isn't showing up in our requirements.txt when we export the
requirements, so the Lambda function is failing because it's missing
this dependency.
=> Add fsspec as an explicit dependency

services/api/src/unified_graphics/static/css/default.css, services/api/src/unified_graphics/static/css/reset.css, services/api/src/unified_graphics/static/css/utility.css, services/api/src/unified_graphics/templates/layouts/diag.html
Add headings for each of the loops.
=> Add labels to loops in diag display

services/api/package-lock.json, services/api/package.json, services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/src/unified_graphics/static/js/component/ChartMap.js, services/api/src/unified_graphics/static/js/scalardiag.js, services/api/src/unified_graphics/templates/layouts/diag.html, services/api/tests/test_unified_graphics.py
Restore the missing fill colors based on the $O - B$ and $O - A$ to the maps. Adds a new endpoint for retrieving the magnitude of a vector, which we use for the map when we display wind. It also removes the `radiusAccessor` function from the ChartMap component, since we are (at least for now) just drawing the dots at a fixed size. lodas was added to support setting a path string as an attribute on the ChartMap for looking up the value to define the fill color.
=> Map Data is Missing

services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/src/unified_graphics/static/js/component/Chart2DHistogram.js, services/api/src/unified_graphics/static/js/component/ChartHistogram.js, services/api/src/unified_graphics/static/js/component/ChartMap.js, services/api/src/unified_graphics/static/js/diag.js, services/api/src/unified_graphics/templates/includes/header.html, services/api/src/unified_graphics/templates/layouts/diag.html, services/api/tests/test_unified_graphics.py
Implement selections on charts using URL parameters in the data sources for the charts, so that they work with our new server-rendered architecture.
Fixes #232
=> Fix chart brushing

services/api/src/unified_graphics/templates/includes/header.html, services/api/src/unified_graphics/templates/includes/model-dialog.html, services/api/src/unified_graphics/templates/layouts/diag.html
Clean up the Jinja templates for the front end.
Stacked on #261.
=> Template refactor

services/api/package-lock.json, services/api/package.json, services/api/poetry.lock, services/api/pyproject.toml, services/data/poetry.lock, services/data/pyproject.toml
Update dependencies in all services
=> Bump dependencies

services/api/src/unified_graphics/routes.py, services/api/src/unified_graphics/static/js/component/ChartTimeSeries.js, services/api/src/unified_graphics/static/js/scalardiag.js, services/api/src/unified_graphics/templates/layouts/diag.html, services/api/tests/test_unified_graphics.py
Create a web component for visualizing time series.
Stacked on #272
=> Time Series Chart

CONTRIBUTING.md
=> Add instructions on how to access the prod logs

CONTRIBUTING.md
Prettier was unhappy with the formatting in CONTRIBUTING.md, which was blocking our build. This is annoying.
=> Fix formatting on CONTRIBUTING.md

src/unified_graphics/diag.py
2 weeks still seems to cause a timeout in production, so I'm going to ratchet this way down just to see if I can get things working, and from there we can see about what resources we need to get a wider window.
=> Reduce window for time series to 2 days

.dockerignore, docker/webserver/Dockerfile
Addresses some security issues we were seeing from Trivy.
=> Update the nginx image to the latest
