NOAA-GSL/unified-graphics

.github/workflows/ui-cleanup-pr-images.yaml, .github/workflows/ui.yaml, services/ui/playwright.config.js
Set up GitHub actions for the UI service.
This PR adds two workflows:
1. To lint, check, test, build and scan the UI service using the npm scripts in `package.json`
2. To clean up PR images for closed PRs
The first workflow will build PR images for preview deployments as well as images for the main branch and for tags like `x.y.z` or `x.y.z-rc#`. It will also use Trivy to scan for critical & high vulnerabilities in the container image and upload them for viewing in GitHub's Security tab.
=> Setup GitHub Actions for the UI service

.github/workflows/api-cleanup-pr-images.yaml, .github/workflows/api.yaml
Set up GitHub Actions for the API service
Add two workflows:
1. To lint, type-check, test, build and scan the API service
2. To clean up PR images for closed PRs
The first workflow will build PR images for preview deployments as well
as images for the main branch and for tags like `x.y.z` or `x.y.z-rc#`.
It will also use Trivy to scan for critical & high vulnerabilities in
the container image and upload them for viewing in GitHub's Security
tab.
=> Setup GitHub Actions for the API service

.github/workflows/api.yaml, .github/workflows/ui.yaml, services/ui/playwright.config.js
The first CI run revealed:
- The `extract_git_ref.py` script wasn't available to the Scan job
- Playwright was being installed incorrectly for the UI tests
- `playwright.config.js` needed to be linted.
=> Fix issues found in first CI run

.github/workflows/api.yaml, .github/workflows/check-ci.yaml, .github/workflows/ui.yaml
This change sets up GitHub Actions to pull the new image tag from GHCR, retag it, and push it to the AWS ECR registry specified in the `vlab` environment
=> Configure CI to deploy to ECR

.github/workflows/api.yaml, .github/workflows/ui.yaml
However, make sure that the scan results are always uploaded to GitHub's Security tab.
=> Block the deploy job if Trivy finds vulnerabilties

.github/workflows/api-cleanup-pr-images.yaml, .github/workflows/ui-cleanup-pr-images.yaml
It appears that environment variables aren't valid in GitHub Action "with:" statements. Switch to using the same variable but from the `github` context - which is available in the `jobs.<job_id>.steps.with.<with_id>` workflow key.
See: https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
=> Fix PR image cleanup in Actions

services/ui/package-lock.json, services/ui/package.json
Version 1.21.0 depended on jpeg-js, which had a security vulnerability
that Dependabot was warning us about. Bump up to 1.23.0, which
apparently has 0 dependencies.
=> Update playwright to 1.23.0

services/ui/src/lib/components/VariableDiag/Histogram.svelte, services/ui/src/lib/components/VariableDiag/Observations.svelte, services/ui/src/lib/components/VariableDiag/VariableDiag.svelte, services/ui/src/styles/_global.scss, services/ui/tests/unit/VariableDiag.spec.js
Calculate the domain and range for both histograms in the VariableDiag
component and pass that down to the histograms, rather than letting each
histogram fit its data. This makes it easier to compare the
distributions between the two minimization loops.
=> Define a shared domain/range for histograms

services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/tests/conftest.py, services/api/tests/test_diag.py, services/api/tests/test_unified_graphics.py
Define the API for fetching wind speed and direction diagnostics.
=> Wind Diagnostics API

services/api/src/unified_graphics/routes.py
The route is not temperature-specific anymore, so we should use a more
generic name for the function.
This should have been part of the temperature refactor, but I didn't
notice the function name until after I merged. This is why we like code
reviews.
=> Rename diag_temperature route function to diagnostics

services/api/src/unified_graphics/diag.py, services/api/tests/test_diag.py, services/api/tests/test_unified_graphics.py
Include coordinates for the observations in the diagnostic data returned by the wind API so that we can plot the wind vectors on a map.
=> Wind observation coordinates

services/api/Dockerfile, services/ui/default.conf.template
The vectorized wind data is large, increase timeouts in gunicorn and in
Nginx from the defaults (30 seconds and 60 seconds, respectively) to 600
seconds.
=> Increase timeouts for large requests

services/ui/src/js/components/VectorMapDiag.js
I've added a basic color ramp with ticks to indicate the Obs - Forecast
for wind speed to the map. It's not great, but it at least helps you
interpret the map. I think we're due for a refactor as this web
component is getting gnarly.
=> Add a legend to the map

services/ui/src/js/components/Chart/Chart2DHistogram.js, services/ui/src/js/components/DiagnosticView/DiagnosticView.svelte
The diagnostic display for vector variables was empty. This PR fixes that bug, although brushing on the map is still broken for both scalars and vectors.
=> Fix vector variable diagnostic display

services/ui/src/js/components/Chart2DHistogram/Chart2DHistogram.js, services/ui/src/js/components/ChartHistogram/ChartHistogram.js, services/ui/src/js/components/ChartMap/ChartMap.js, services/ui/src/js/components/DiagnosticView/DiagnosticView.helpers.js, services/ui/src/js/components/DiagnosticView/DiagnosticView.stores.js, services/ui/src/js/components/DiagnosticView/DiagnosticView.svelte, services/ui/src/js/components/DiagnosticView/LoopDisplay.svelte
Add support for brushing the histogram and heatmap. Fix the brushing on the map.
=> Add brushing on all charts

services/api/poetry.lock, services/api/pyproject.toml
pytest 5.4 had a dependency on the "py" library. This was triggering our vulnerability scanners. The latest version of pytest has dropped the dependency on "py" so will fix the issue. This is a dev dependency so there is some debate on if this is really necessary. However, it seems important to get the container deployed before the demo and this is the easiest path forward.
=> Update pytest to the latest

services/ui/src/js/components/ChartContainer/ChartContainer.js
With the new design for displaying the loading icon, we stopped destroying and recreating our charts on every variable selection. We only create new charts if the element type actually changes. But our mutation observer wasn’t configured correctly, so when we swapped out the histogram for the heatmap, the heatmap never got dimensions because the chart-container didn’t notice. Therefore, the distributions stopped rendering.
=> Fix chart rendering when variable type changes

services/api/poetry.lock, services/api/pyproject.toml, services/api/src/unified_graphics/diag.py, services/api/tests/conftest.py, services/api/tests/test_diag.py
We're using moto in server mode as a local S3 service. This is similar to how the s3fs library runs its tests. I ended up needing to modify the code that opens files in S3 to allow us to inject a non-AWS endpoint for S3 and to specify the path used for the local cache.
Making sure that `fsspec.open()` was being called correctly in the tests was more involved than I would have liked. We had to make sure that AWS was being properly mocked out and that the local cache was being cleared in between tests.
=> Add unit tests to the S3 code

.githooks/pre-commit, .github/workflows/api.yaml, CONTRIBUTING.md, services/api/Dockerfile, services/api/poetry.lock, services/api/pyproject.toml, services/api/src/unified_graphics/__init__.py, services/api/src/unified_graphics/routes.py, services/api/tests/test_diag.py
Update the API service to Python 3.11. While we're at it, add isort to organize our dependencies.
=> Update to Python 3.11

services/ui/src/js/components/Chart2DHistogram/Chart2DHistogram.js, services/ui/src/js/components/ChartHistogram/ChartHistogram.js, services/ui/src/js/components/ChartMap/ChartMap.js, services/ui/src/js/components/ColorRamp/ColorRamp.js, services/ui/src/js/components/DiagnosticView/DiagnosticView.svelte, services/ui/src/js/components/DiagnosticView/LoopDisplay.svelte
Convert the color scale for the map from a continuous scale to a quantized one.
I think the binned values will be easier to read off of the map. I also fixed
the issue with the legend for the map always being titled "speed" (#124).
=> Use a quantized color scale for the bubble map

services/ui/src/js/components/DiagnosticView/LoopDisplay.svelte
This prevents multiple selections — one on the map and one on the
histogram — from being applied simultaneously, which creates kind of a
weird state where the data shown on the histogram includes more data
than is included on the map.
=> Reset the selections when any selection is changed

services/ui/src/js/components/ChartHistogram/ChartHistogram.js, services/ui/src/js/components/DiagnosticView/LoopDisplay.svelte
Fix the formatting for the annotations on the histograms. Reposition the
annotations so that they don't overlap with the observation count in the chart
and so that they are less likely to be clipped by the edges of the chart. The
labels have been made bold and given a slight text shadow to increase contrast
against the background, but more work will likely be needed to improve
legibility.
=> Format histogram annotations

.github/dependabot.yml
Currently, only use [Dependabot on GitHub Actions (GHA)](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot). If we want, we can turn Dependabot on for npm & Poetry/pip in the future.
=> Turn on dependabot for GitHub Actions

services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/tests/conftest.py, services/api/tests/test_unified_graphics.py, services/ui/src/js/App.svelte, services/ui/src/js/components/DiagnosticView/DiagnosticView.svelte, services/ui/src/js/components/DiagnosticView/LoopDisplay.svelte, services/ui/src/js/components/Header/Header.svelte
Update the application to fetch available model initialization times based on
what's available in a Zarr array and allow users to select the init time they'd
like to see.
This PR is stacked on #147.
=> Model init time selection

.github/workflows/api.yaml, .github/workflows/data.yaml, .github/workflows/ui.yaml
The data service pipeline wasn't granting the permissions Dependabot needed and we don't really need to send the Dependabot container images to VLab.
=> Fix CI for dependabot

.github/workflows/api-cleanup-pr-images.yaml, .github/workflows/api.yaml, .github/workflows/data-cleanup-pr-images.yaml, .github/workflows/data.yaml, .github/workflows/ui-cleanup-pr-images.yaml, .github/workflows/ui.yaml
They are valid YAML though. That's what I get for using a linter.
https://docs.github.com/en/actions/learn-github-actions/expressions#literals
=> Double quotes aren't valid in GitHub Actions literals

services/data/src/ugdata/aws.py, services/data/tests/test_aws.py
We should really convert this to a real logging handler, but we just
need a quick fix to see why the events we're getting in Lambda are
missing the "Records" key.
=> Log non-test events that have no Records key

services/data/src/ugdata/aws.py, services/data/tests/test_aws.py
We're not getting the kinds of events we expected from the S3 events.
Ian thinks this may have to do with the fact that VLab had to use
EventBridge to hook up our lambda function. The format we're expecting
now is the format we logged from the handler when we didn't get what we
expected, so hopefully this works.
=> Change Lambda handler for EventBridge events

services/ui/src/index.html, services/ui/src/js/main.js, services/ui/src/public/serviceworker.js, services/ui/src/styles/_default.scss
Implement a service worker to help cache data and speed up the application. The service worker intercepts all of our HTTP requests and prefers serving them from the application cache over network fetches. The service worker cache should hold onto things more reliably than the regular browser cache.
Additionally, we use the service worker to reduce duplicate network requests to cut down on bandwidth and ease the burden on our server.
After the first load when the service worker is installed, there is a dramatic increase in speed for the application even over slow network connections.
=> Add Service Worker

services/api/src/unified_graphics/static/serviceworker.js
We should only cache a response if it’s OK (200–299). Anything outside
of that range and we should not cache it. We don’t want to always have a
redirect or an error for a certain URL.
=> Check response status before caching responses

services/api/src/unified_graphics/static/serviceworker.js
Prioritize the network for HTML documents, rather than using cached documents.
The HTML includes a <select> element for picking initialization times, which can
update fairly frequently. We don’t want someone seeing a stale list of available
runs just because they loaded up a run they looked at yesterday.
=> Network-first strategy for HTML caching

.gitignore
I have a KDL file in my project root to configure a project-specific Zellij
workspace. Tired of seeing it come up in `git status`.
=> Ignore Zellij kdl files

services/api/poetry.lock, services/api/pyproject.toml
I’m doing this update manually because there were some conflicts in the
dependabot PR that made me antsy.
=> Bump mypy from 1.0.1 to 1.1.1

services/api/src/unified_graphics/diag.py, services/api/src/unified_graphics/routes.py, services/api/src/unified_graphics/static/js/component/ChartTimeSeries.js, services/api/src/unified_graphics/static/js/scalardiag.js, services/api/src/unified_graphics/templates/layouts/diag.html, services/api/tests/conftest.py, services/api/tests/test_unified_graphics.py
Implement the API for retrieving historical summaries of model runs.
- #283
=> Time series visualization

services/api/src/unified_graphics/diag.py
Reading the arrays out of the Zarr in S3 was so slow it was causing
gateway timeouts. It looks like reading the consolidated metadata is
much faster, and should hopefully unstick the application in production
until we can implement some more performant data handling.
=> Switch to read_consolidated in get_model_metadata

.github/dependabot.yml
The weekly scans were getting quite noisy. Unfortunately there doesn't appear to be a way to do security updates weekly while reducing version updates to a monthly run. The GitHub Actions check hasn't been as noisy so it seems okay to leave that at a weekly cadence.
=> Reduce Dependabot version updates to once a month

services/api/Dockerfile
Gunicorn recommends using 2-4*num_cores workers. Starting conservatively with 4 workers. Unfortunately Docker's `CMD` directive won't expand environment variables when used with JSON syntax. We could use the `CMD` directive in shell mode in order to expand the env variable. However, that has its own issues with PID reaping which is something Gunicorn handles when it's called with JSON syntax and given PID 1.
=> Increase the number of workers in the API service

services/data/src/ugdata/aws.py, services/data/tests/test_aws.py
Get the prefix to strip from a `UG_DIAG_KEY_PREFIX` environment variable. If no environment variable is set, don't strip any prefixes.
=> Add support for stripping prefixes from the S3 key

.github/dependabot.yml, services/api/Dockerfile, services/api/Dockerfile-webserver
Switch the API and UI images to run as a non-root user. Use UID & GID 1000 to match VLab's preferences in the API image and use the built-in nginx user (uid/gid 101) in the `nginx-unprivileged` image. Additionally, switch our Python image to be based on a debian-slim variant to reduce image size and possible security issues.
=> Switch our images to non-root users

src/unified_graphics/__init__.py
Now that we have converted the application to a monolith instead of having separate frontend and API services, we no longer need the CORS header.
=> Remove the CORS middleware for dev

src/unified_graphics/static/css/default.css, src/unified_graphics/templates/includes/header.html
Make it clear that the model data on display is from experimental versions of the models. This may actually be something we want to capture in the database in the future, in case we display non-experimental models as well.
=> Add an experimental label to the site

src/unified_graphics/etl/aws.py, src/unified_graphics/etl/diag.py
AWS has "helpfully" provided a default logger instance in their image. I needed to strip it out with `force:  True` in the logging config so that we could configure our own logger. There may be a better way to handle this but for now, this works.
=> Add a logger to our lambda function

src/unified_graphics/etl/aws.py, src/unified_graphics/etl/diag.py
We now are using the database for this purpose. We also suspect that this is an expensive operation and is causing our Lambda ETL functions to timeout.
=> Don't generate consolidated metadata for Zarr

src/unified_graphics/etl/diag.py, tests/etl/test_extract.py, tests/etl/test_save.py
To ensure that our Zarr groups have a uniform format, we append ":00" to the init time if the ingested NetCDF file has only a year, month, day, and hour for the init time.
=> Always include minutes in initialization time

src/unified_graphics/templates/layouts/diag.html
Retrieving the data for the time series is not performant because of our storage structure. It routinely times out in production. So for now I’m removing it until we can get the performance fixed.
=> Remove the time series for now

poetry.lock, pyproject.toml, src/unified_graphics/etl/diag.py, tests/conftest.py, tests/etl/test_save.py
Add storage of diag data as partitioned Parquet files. This should be more suitable for our time series visualizations.
=> Parquet data storage

src/unified_graphics/etl/diag.py, tests/etl/test_save.py
I think there's something wrong with writing Parquet from our Lambda function. Until we get that sorted, I'm reverting this because it's holding up the data pipeline.
=> Don't write Parquet files during etl

.github/workflows/api.yaml
This speeds up test collection tremendously. Pytest takes about 2 minutes to check the entire project for tests, but if we point it at the tests/ directory, it takes 0.11s to collect all the tests. Since we don't have doctests in the code, there's no reason to have pytest check the whole project.
=> Point pytest to our tests directory

.github/workflows/api.yaml
Add `tests/**/*` to the paths we check for changes when running CI, so that if we are just changing tests, they run in the PR. We don't want to accidentally break tests just because we didn’t change the application.
=> Run CI whenever anything in tests/ changes

.github/workflows/api.yaml, poetry.lock, pyproject.toml, tests/conftest.py, tests/etl/test_extract.py, tests/etl/test_save.py, tests/test_diag.py, tests/test_unified_graphics.py
Cleaning up test organization and fixtures in an attempt to make the tests clearer and easier to write.
Removed a number of global fixtures from `conftest.py` that aren’t needed globally. All of the Flask app fixtures are moved to the `test_unified_graphics.py` module. I eliminated some of the old fixtures for generating test data in favor of the `test_dataset` fixture which is more flexible.
I also tried to ensure that every test only asserts one condition, using the [class pattern for safely asserting multiple statements][1]. This way one failed assertion doesn't mask other failed conditions; if multiple conditions are failing in a test, we will be notified by all of them at once.
Finally, I eliminated the `--runaws` flag by adding `moto` for mocking an S3 server locally for our tests. …
=> Test clean up

.github/workflows/api.yaml, .github/workflows/ui.yaml, docker/app/Dockerfile, pyproject.toml
The `--dev` option is deprecated in favor of Poetry dependency groups. The Poetry CLI flag is also being updated so change our Docker images to use `--without dev` instead of the deprecated `--no-dev`.
This change also adds CI triggers for when our `pyproject.toml` file and `Dockerfile`'s are updated.
=> Switch dev dependencies to Poetry groups

.github/dependabot.yml
Our repo was reorganized in merge commit 7258fe206230141ac4648d2a245e89bd68c22fcf. However, Dependabot wasn't updated to use the new repo structure. Fix that, add a default assignee for version updates and experiment with Dependabot's new "groups". Hopefully, grouping version updates will help keep the number of PRs from exploding.
=> Update Dependabot to use the new repo structure

.dockerignore, .github/dependabot.yml
The group names are used in PR titles so make them more descriptive.
Additionally, update the `.dockerignore` file to exclude `tmp/` directories.
=> Update dependabot group names

src/unified_graphics/etl/aws.py, src/unified_graphics/etl/diag.py, tests/etl/test_aws.py, tests/etl/test_save.py
It looks like the error we were getting in our Lambda function is related to the “..” in the filename that was reusing the Zarr path to find where to write the Parquet file.
The problem can be fixed by using `os.path` to strip off the Zarr filename and replace it with the Parquet directory so that there is no “..” in the path passed to pyarrow. I’m not entirely sure that this is a good plan at this juncture, however, because it’s unlikely we’ll get the time series data back in place before I’m on leave, so we’ll just be writing these Parquet files and taking up space in S3 for no reason.
Instead, I think it’s worth investigating replacing Zarr and Postgres with Parquet for diag data. (I suspect Zarr will still be a great solution for the forecast data output by the models.)
=> Fix Parquet failure in AWS

src/unified_graphics/diag.py, src/unified_graphics/routes.py, src/unified_graphics/static/js/component/Chart2DHistogram.js, src/unified_graphics/static/js/component/ChartHistogram.js, src/unified_graphics/static/js/component/ChartMap.js, src/unified_graphics/templates/layouts/diag.html, tests/test_diag.py, tests/test_unified_graphics.py
Optimize the backend that generates the JSON from the Zarr and Parquet files. All of the list comprehensions in Python that were generating the GeoJSON responses were really slowing down our responses. By changing the response format and relying on `pandas.DataFrame.to_json` so that we can eliminate those loops, we get significantly faster responses (0.3s instead of 20s).
=> Optimize JSON responses

.github/workflows/api.yaml, .github/workflows/ui.yaml
Now that we have dependabot to keep our GitHub Actions up-to-date, switch to using a specific Trivy release. 
Additionally, the latest Trivy release fixed a bug that was hiding a misconfiguration in our pipelines. For some reason, the GitHub Action Trivy publishes has decided to diverge from its CLI tool's behavior and ignore the `severity: CRITICAL,HIGH` configuration unless the `limit-severities-for-sarif: true` option is also set. When coupled with the `exit-code: 1` config option we had set, this meant Trivy would exit with an error code of 1 when it found any vulnerability, not just a critical or high vulnerability like we were anticipating.
=> Fix Trivy CI failures

src/unified_graphics/diag.py, src/unified_graphics/static/js/component/ChartMap.js, src/unified_graphics/static/js/component/ChartTimeSeries.js, tests/test_diag.py, tests/test_unified_graphics.py
Replace the mean line with the median, and display Q1 and Q3 in addition to min and max to provide a better sense for the distribution of observations.
=> Display median o - b and quartiles

src/unified_graphics/diag.py, src/unified_graphics/routes.py, src/unified_graphics/templates/layouts/diag.html, tests/test_diag.py, tests/test_unified_graphics.py
Limit the amount of data read in for the historical data to just two weeks prior to the initialization time. This should reduce memory usage in production and allow the application to continue working, solving #443 (I hope).
In future, we may make this range configurable by users, instead of hard-coding a two week limit.
=> Limit time series display to 2 weeks

src/unified_graphics/diag.py
Replace "/".join() with os.path.join() to build the path for the Parquet file in S3. Unlike a file system, it seems that having a double "//" in the path is breaking the S3 access in Pandas.
=> Use os.path.join in diag.diag_observations

src/unified_graphics/static/js/component/ChartOMBHistory.js, src/unified_graphics/static/js/component/ChartObsCount.js, src/unified_graphics/static/js/scalardiag.js, src/unified_graphics/static/js/vectordiag.js, src/unified_graphics/templates/layouts/diag.html
Hacked in another line chart to display the count of used observations per run.
=> Display historical counts of observations used

src/unified_graphics/static/js/component/ChartMap.js
Create a GeoJSON FeatureCollection from the data that we can pass to D3's fitSize method to zoom the map to the data.
I tried using d3.extent to find the range of the longitude and latitude in the data from which I created a FeatureCollection with just 2 points, but the longitude range ended up being nearly [-180, 180], so it never actually zoomed the map. Seems like maybe D3 is doing something smart to handle collections that wrap around the globe, or possibly there's some unaccounted for weirdness in the data.
Fixes #447
=> Fit the map to the data

.github/dependabot.yml
Since this project is on a hiatus, reduce the frequency of our dependabot version updates. Security updates will still be opened promptly.
=> Reduce dependabot updates to once a month

docker/app/Dockerfile, poetry.lock, pyproject.toml
This change updates all Python dependencies except pytest as pytest 8 causes test failures that need more in depth debugging. It also updates the Dockerfile for the `app` image to make sure that some Python internals (`setuptools`, `pip`, and `wheel` are up-to-date.
=> Bump dependencies
